backend:
  name: github
  repo: manuelhier/pia-blog
  branch: main
  base_url: https://pia-blog-cms-auth.dev-bc7.workers.dev

media_folder: 'assets/uploads'

collections:
  - name: 'Posts'
    label: 'posts'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - { label: 'Titel', name: 'title', widget: 'string', collapsed: true}
      - { label: 'Datum', name: 'date', widget: 'datetime', time_format: false }
      - { label: 'Kategorien', name: 'categories', widget: 'list', collapsed: true, required: false}
      - { label: 'Tags', name: 'tags', widget: 'list', collapsed: true, required: false}
      - { label: 'Cover', name: 'cover', widget: 'image', collapsed: true, required: false}
      - { label: 'Beschreibung', name: 'description', widget: 'string', collapsed: true, required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  # - name: "pages"
  #   label: "Seiten"
  #   folder: "_pages"
  #   create: true
  #   slug: "{{slug}}"
  #   fields:
  #     - { label: "Titel", name: "title", widget: "string", required: false}
  #     # - { label: "Permalink", name: "permalink", widget: "string", required: false, hint: "z.B. /ueber-mich/" }
  #     - { label: "Inhalt", name: "body", widget: "markdown" }
  # - settings:
  #   label: 'Einstellungen'
  #   folder: '_data/'
  #   create: false
  #   editor:
  #     preview: false
  #   files: 
  #     - label: 'Config'
  #       name: 'config'
  #       file: 'settings.yml'
  #       fields:
  #         # - { label: 'Titel', name: 'title', widget: 'text', default: 'about' }
  #         # - { label: 'E-Mail', name: 'email', widget: 'text', default: 'about' }
  #         # - { label: 'Navigation', name: 'description', widget: 'list' }

